services:
  create_blog_pr:
    container_name: create_blog_pr
    build:
      context: .
      dockerfile: create_blog_pr.Dockerfile
      args:
        - no-cache=true
    environment:
      - GITHUB_SECRET_KEY=${GITHUB_SECRET_KEY}
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
      - POSTGRES_URL=${POSTGRES_URL}
    networks:
      - s-dev-network

  create_mypage_pr:
    container_name: create_mypage_pr
    build:
      context: .
      dockerfile: create_mypage_pr.Dockerfile
      args:
        - no-cache=true
    environment:
      - GITHUB_SECRET_KEY=${GITHUB_SECRET_KEY}
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
      - POSTGRES_URL=${POSTGRES_URL}
    networks:
      - s-dev-network

networks:
  s-dev-network:
    external: true
