name: build
permissions:
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
          run_install: false

      - name: Get pnpm directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: pnpm i --frozen-lockfile
      - run: pnpm check:ci
      - run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true
      - run: pnpm test
      - name: Show coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@7727b0282e61c3cffa400550cf2ae57c2b16167d # v2
        with:
          json-summary-path: ./.vitest-coverage/coverage-summary.json
          json-final-path: ./.vitest-coverage/coverage-final.json

      # - run: pnpm test:e2e # FIXME: later if I have time
      - run: pnpm storybook:build
        env:
          SKIP_ENV_VALIDATION: true
      - run: pnpm build
        env:
          SKIP_ENV_VALIDATION: true
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
