# FIXME: refactor for multiple declation and cache
# FIXME: skip env 不要
name: ci
permissions:
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-build-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          # version: X.X.X
          # Optional when there is a packageManager field in the package.json.
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: npx vercel@latest env run -e development --token=${{ secrets.VERCEL_TOKEN }} -- pnpm build
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  biome:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-biome-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: pnpm check:ci

  eslint:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-eslint-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: npx vercel@latest env run -e development --token=${{ secrets.VERCEL_TOKEN }} -- pnpm lint
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          SKIP_ENV_VALIDATION: "true"

  knip:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-knip-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: pnpm knip

  test:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-test-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Get pnpm directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

      - run: pnpm i --frozen-lockfile
      - run: pnpm --filter "./packages/*" build
      - run: pnpm exec playwright install
      - run: npx vercel@latest env run -e development --token=${{ secrets.VERCEL_TOKEN }} -- pnpm test
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Show coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@2500dafcee7dd64f85ab689c0b83798a8359770e # v2
        with:
          json-summary-path: ./.vitest-coverage/coverage-summary.json
          json-final-path: ./.vitest-coverage/coverage-final.json

  storybook:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-storybook-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          # version: X.X.X
          # Optional when there is a packageManager field in the package.json.
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: npx vercel@latest env run -e development --token=${{ secrets.VERCEL_TOKEN }} -- pnpm storybook:build
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          SKIP_ENV_VALIDATION: "true"

  docker-build-storybook:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-docker-build-storybook-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build storybook Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          file: ./.storybook/storybook.Dockerfile
          push: false

  docs:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-docs-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile

      - name: Build TypeDoc
        run: pnpm docs:build
