name: ci
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        check: [build, supplemental-lint, storybook, docs, schema-locked]
    permissions: {}
    uses: ./.github/workflows/ci-check.yaml
    with:
      check: ${{ matrix.check }}

  reporting-checks:
    strategy:
      fail-fast: false
      matrix:
        check: [oxfmt, lint, knip, test]
    permissions:
      pull-requests: write
    uses: ./.github/workflows/ci-check.yaml
    with:
      check: ${{ matrix.check }}
      reporting: true
