name: license-check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: ./.github/actions/setup-pnpm

      - name: Generate license summary
        run: pnpm license:summary

      - name: Check for forbidden licenses
        run: pnpm license:check
