name: mutation-test
permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "packages/core/**/*.ts"
      - "stryker.config.json"
jobs:
  mutation-test:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: pnpm test:mutation:core

      - name: Upload mutation report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: mutation-report
          path: reports/mutation/
          retention-days: 14
