name: prisma-deploy
permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - "packages/database/prisma/migrations/**"
jobs:
  prisma-deploy:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: pnpm --filter s-database prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
