name: prisma-deploy
permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - "packages/database/prisma/migrations/**"
  workflow_dispatch:
jobs:
  prisma-deploy:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          submodules: true

      - uses: ./.github/actions/setup-pnpm
      - run: pnpm --filter s-database prisma:generate
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}
          DIRECT_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}
      - run: pnpm --filter s-database prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}
          DIRECT_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}
