name: update-submodules

on:
  # schedule:
  #   - cron: "0 23 * * 1"
  workflow_dispatch:

jobs:
  update-submodules:
    permissions: {}
    uses: s-hirano-ist/s-templates/.github/workflows/update-submodule.yaml@9f835cbeb6b2457d3fc0cf3a8bf7b906a8af639b
